### ISSUE TITLE
UNICODE Username in HORDE

### ISSUE THREAD

**Issue by prakash5331** [mrubinsk/horde_blocks#1]
Hi,

We are working on IDN mail services.
We are able to send and receive mail using non-ascii email id but we have no GUI interface through which we can add non-ascii username.
Now we installed HORDE Groupware 5.2.10 with mysql and we are able to add username but when we checked database horde_user then found non-ascii username converted into ""??????".
But when I write a code in PHP and execute it manully then it's insert perfectly .

$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
@mysql_query("SET NAMES 'utf8'",$id);
$sql = "INSERT INTO horde_users (`user_uid`,`user_pass`)
VALUES ('नितिन', 'nzvBuHphCWhHLM6fhTnUfDuLtA1dOWVJ')";
$cresult = @mysql_query($sql,$id);
if ($conn->query($sql) === TRUE) {
    echo "New record created successfully";
} else {
    echo "Error: " . $sql . "<br>" . $conn->error;
}

Now we checked it in HORDE then it show me à¤¨à¤¿à¤¤à¤¿à¤¨ (unreadable character)

Regards,
Chandra prakash

**Comment by mrubinsk** [comment]
Closing, as this has nothing to do with this repository.
